image: sikalabs/ci

stages:
  - check
  - build
  - test
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

editorconfig check:
  stage: check
  image: mstruebing/editorconfig-checker
  script:
    - ec

gofmt:
  stage: check
  image: golang:1.17
  script:
    - gofmt -d -l .

build docker:
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t $IMAGE .
    - docker push $IMAGE

build bin:
  stage: build
  parallel:
    matrix:
      - GOOS:
          - windows
          - linux
          - darwin
        GOARCH:
          - amd64
          - arm64
  image: golang:1.17
  script:
    - export CGO_ENABLED=0
    - go build -o server-$GOOS-$GOARCH app.go
  artifacts:
    paths:
      - server-*

deploy:
  stage: deploy
  needs:
    - build docker
  script:
    - helm upgrade --install
        main one-image
        --repo https://helm.sikalabs.io
        --create-namespace
        --namespace $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
        --set image=$IMAGE
        --set host=$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop

stop:
  stage: deploy
  when: manual
  variables:
    GIT_STRATEGY: none
  script:
    - helm uninstall
        main
        --namespace $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
  environment:
    name: $CI_COMMIT_REF_SLUG
    action: stop
